### ISSUE TITLE
Feature request: add option to disable the confirm password input

### ISSUE THREAD

**Issue by caendesilva** [jeffgreco13/filament-breezy#109]
Hey there! First of all, thanks for making such a great package!

I see that the password confirmation input is hard-coded in the Register.php form schema. There are a lot of criticism regarding a field like this. I think it would be really nice to have the configuration option to disable it. Maybe by using a `->when()` method chain?

See [uxmovement.com](https://uxmovement.com/forms/why-the-confirm-password-field-must-die/#:~:text=Many%20think%20the%20confirm%20password,to%20type%20their%20password%20twice.), [ux.stackexchange.com](https://ux.stackexchange.com/questions/484/is-a-repeat-password-field-necessary-in-a-signup-page), and [about 377 000 000 more results on Google](https://www.google.com/search?q=should+you+have+a+password+confirmation+input&oq=should+you+have+a+password+confirmation+input&aqs=chrome..69i57j33i160.7016j0j7&sourceid=chrome&ie=UTF-8).

An additional feature that I think would be amazing that is useful both when there is a confirmation field and not is to have a way to show the password in plain text as is suggested in [Sign-in form best practices at web.dev](https://web.dev/sign-in-form-best-practices/#show-password) as this is great for both UX and accessibility. 
![image](https://user-images.githubusercontent.com/95144705/187046266-575bb3f5-044d-4d33-b173-98d22ac1478c.png)

Sidenote, on the issues page there are links to create discussions, however, the discussion page is not enabled.

**Comment by caendesilva** [comment]
Update: as a workaround I changed the registration page with an override as follows, in case anyone else wants to do this.

```php
<?php

namespace App\Http\Livewire\Auth;

use Filament\Forms;
use JeffGreco13\FilamentBreezy\FilamentBreezy;

class Register extends \JeffGreco13\FilamentBreezy\Http\Livewire\Auth\Register
{
    protected function getFormSchema(): array
    {
        return [
            Forms\Components\TextInput::make('name')
                ->label(__('filament-breezy::default.fields.name'))
                ->required(),
            Forms\Components\TextInput::make('email')
                ->label(__('filament-breezy::default.fields.email'))
                ->required()
                ->email()
                ->unique(table: config('filament-breezy.user_model')),
            Forms\Components\TextInput::make('password')
                ->label(__('filament-breezy::default.fields.password'))
                ->required()
                ->password()
                ->rules(app(FilamentBreezy::class)->getPasswordRules()),
        ];
    }
}
```

**Comment by jeffgreco13** [comment]
Closing to prepare for Filament v3. Nice solution
