### ISSUE TITLE
Pull request #116 breaks email verification

### ISSUE THREAD

**Issue by ashleyhood** [jeffgreco13/filament-breezy#119]
The pull request #116 that was merged breaks email verification because it added the `__construct` method which added [authentication middleware](https://github.com/EzimetYusup/filament-breezy/blob/bfde1077b851983b817d5d21e222b81a703612e3/src/Http/Controllers/EmailVerificationController.php#L15) but the middleware was not namespaced correctly and breaks as it is looking for `JeffGreco13\FilamentBreezy\Http\Controllers\Authenticate` class. Should be `Filament\Http\Middleware\Authenticate::class`.

**Comment by EzimetYusup** [comment]
@ashleyhood @jeffgreco13

**Comment by ashleyhood** [comment]
Thanks @EzimetYusup this has solved the issue :smile:
