### ISSUE TITLE
Break up profile form into separate components

### ISSUE THREAD

**Issue by boris-glumpler** [jeffgreco13/filament-breezy#122]
Hello,

more of a question really. Wouldn't it make sense to split up the profile form into separate components? That way we could just use these components if we want to add sections to the profile. Right now we have to publish the whole profile template. This also means that any changes that happen in the future have to be manually re-added to the published template. 

Cheers!

**Comment by jeffgreco13** [comment]
Reviewing your PR. I think this is fine, will just do some testing.
