### ISSUE TITLE
Hyperlinks to registration page

### ISSUE THREAD

**Issue by KonradHambuch** [jeffgreco13/filament-breezy#132]
In case I would like to add a hyperlink on a non-filament page to the registration page (e.g. on my landing page), this hyperlinks don't work. (```<a href="/admin/register">Sign up</a>```)

The hyperlink to the login page works well and then from there the navigation link to the registration also works fine. But not from outside of filament.

After I once go through the login page to the registration, it starts also work from the landing page. It feels like the registration page is not created on boot or something.

(registration url is also fine when typed in manually)

**Comment by jeffgreco13** [comment]
A bit late, so I hope you found a solution to your problem.
If you can confirm that you are logged out, I cannot see any reason that you are not able to link directly to the register page from anywhere.
First, use `php artisan route:list` to check the route for the Register page (after you install Breezy). Then, create a link to the full path for the register page.

Please note: if the user is currently logged in, it will redirect them to the 'home_url' value. Here's the snippet in [Register.php](https://github.com/jeffgreco13/filament-breezy/blob/v1.5.2/src/Http/Livewire/Auth/Register.php) that handles the redirect:

```php
    public function mount()
    {
        if (Filament::auth()->check()) {
            return redirect(config("filament.home_url"));
        }
    }
```

**Comment by KonradHambuch** [comment]
Oh, OK that is the problem, I haven't solved it until now. That's not the best solution if I have a frontpage outside of Filament. But thank you for your help very much. I replaced the home url to /admin in my config.
