### ISSUE TITLE
[FR] Browser sessions management UI

### ISSUE THREAD

**Issue by billmn** [jeffgreco13/filament-breezy#138]
Is there any plan to implement browser sessions management UI like in Laravel Jetstream?

https://jetstream.laravel.com/2.x/features/browser-sessions.html

**Comment by Saifallak** [comment]
this requires users to use DB for sessions.
is there a way to manage sessions based on files?

**Comment by billmn** [comment]
No, the only way is to use database session driver. 

This UI should be optional and enabled by users that use db session driver. 

This would avoid having to implement session management every time.

**Comment by jeffgreco13** [comment]
Hi @billmn thank you for submitting this feature request and apologies for not answering sooner.
There were, and are no plans to implement session management in Breezy v1 but v2 will have a similar feature available. Breezy v2 will be released alongside the Filament v3 beta.
Thanks!

**Comment by stuartcusackie** [comment]
Looks like this was going ahead but then got dropped? The comments are a little confusing.

Anyway, this is a very nice feature of Jetstream and it would be nice to have it. Seems like it would fit in perfectly to Breezy.
