### ISSUE TITLE
No reset password link

### ISSUE THREAD

**Issue by wpas81** [jeffgreco13/filament-breezy#139]
Hi

My logon form does not show a "password reset link". The options in the breezy-config file haven't been changed. Any idea what I missed?

![image](https://user-images.githubusercontent.com/64780854/214516652-d39c0e94-d2f6-4dac-8644-e3f7e626a0bf.png)

**Comment by jeffgreco13** [comment]
Please check `config/filament.php` and make sure you are pointing to the Breezy Login::class component. See the installation docs.

**Comment by wpas81** [comment]
Yes I did. 
![image](https://user-images.githubusercontent.com/64780854/214608600-669ba770-7303-4195-8f9f-0cc8f15b11b4.png)

**Comment by jeffgreco13** [comment]
Can you confirm the Breezy Login component is actually being loaded here? Unless you disabled registration, there is also usually a link to register.
Please also check your confirm against the Breezy config to make sure everything is set correctly: https://github.com/jeffgreco13/filament-breezy/blob/1.x/config/filament-breezy.php. Check password_reset_component_path

**Comment by wpas81** [comment]
that's unchanged. Registration is set to off all other settings were default.

I'm a bit busy the last days, next week i'll make a fresh start & see if that does the trick. Thanks for following up!

**Comment by wpas81** [comment]
man... major facepalm moment here.... It even shows here in my screenshot....

replaced
 //'login' => \Filament\Http\Livewire\Auth\Login::class,
\JeffGreco13\FilamentBreezy\Http\Livewire\Auth\Login::class,
to
	**'login' =>** \JeffGreco13\FilamentBreezy\Http\Livewire\Auth\Login::class,
