### ISSUE TITLE
2 Factor Verification Not Working.

### ISSUE THREAD

**Issue by koti42** [jeffgreco13/filament-breezy#146]
Even though I enter the code I get from the application on the application screen, it constantly says that the 6-digit code I get is incorrect. And I cannot make progress.
![Screenshot_114](https://user-images.githubusercontent.com/58147869/222089569-6a593968-a0a6-4855-80e9-d08b9f950a05.png)

**Comment by koti42** [comment]
I think the authenticator is not working at localhost. I downloaded an authenticator from Google and it worked when I tried with it. Can you give information about this issue, phone applications do not work on localhost?

**Comment by jeffgreco13** [comment]
@koti42 Are you using Valet or Homestead?
Either way, I don't think this should matter. In testing, I was able to authenticate with 2FA on localhost.
If you are using Valet or ngrok, try using a tunnel to see if there's a difference for you.

**Comment by jeffgreco13** [comment]
This should still work on localhost. Apologies for such a delay; am preparing for Filament v3. Is this issue still happening? Any progress?

**Comment by fblaser** [comment]
@koti42 : have you checked if the time is set to the same value on both your computer and the device running the authenticator apps? If they differ too much, you will get the right 6 digit codes, but at the wrong time ;)

**Comment by jeffgreco13** [comment]
Closing this issue until confirmation can be provided.
