### ISSUE TITLE
2FA bypass

### ISSUE THREAD

**Issue by JaZo** [jeffgreco13/filament-breezy#151]
We're setting up Filament with Breezy and want our admins to be able to use 2FA, so we've enabled it in the config. We've also configured admin panel access based on the email domain [as described in the filament docs](https://filamentphp.com/docs/2.x/admin/users#authorizing-access-to-the-admin-panel). Now if a user logs in via Filament it's all working fine. But if the user uses the login page of the app and then goes to Filament there is no 2FA prompt, completely bypassing it. Should we configure someting differently or is this a bug?

**Comment by JaZo** [comment]
FWIW: We've configured a separate guard for Filament to circumvent this issue.

**Comment by jeffgreco13** [comment]
@JaZo I'm going to close this issue as I believe you've solved it with another guard.
Filament v3 is going to open new doors with the ability to create multiple panels, each with their own set of plugins, resources, pages, routes, etc. etc.
Stay tuned. This will be standard functionality in Breezy v2
