### ISSUE TITLE
Target class [filament-breezy] does not exist

### ISSUE THREAD

**Issue by ttungbmt** [jeffgreco13/filament-breezy#159]
![image](https://github.com/jeffgreco13/filament-breezy/assets/12232155/994051ad-4642-46bc-87ad-1a4c135ae48e)
![image](https://github.com/jeffgreco13/filament-breezy/assets/12232155/2e3934e3-5c99-4a19-9d64-87b63d77a44c)

**Comment by fikurimax** [comment]
Any updates?

**Comment by jeffgreco13** [comment]
Can anyone confirm this issue is happening outside of using ide-helper?

**Comment by underdpt** [comment]
Hello,

I've just been hit by this trying to setup a `Password::class` instance to validate passwords, following the readme instructions.

I'm on Laravel 10

**Comment by underdpt** [comment]
Just to clarify, this happens on `artisan package:discover`, I'm not using `ide-helper`. On development and production environments, I have to disable this functionality.

**Comment by underdpt** [comment]
I was able to use this with:

```php

use JeffGreco13\FilamentBreezy\FilamentBreezy;

app(FilamentBreezy::class)::setPasswordRules([
    Password::min(8)
        ->letters()
        ->numbers()
        ->mixedCase()
        ->uncompromised(3),
]);
```
