### ISSUE TITLE
Profile page is not working when working with Tenancy

### ISSUE THREAD

**Issue by tygoegmond** [jeffgreco13/filament-breezy#179]
Hello,

I hope this message finds you well. I am writing to report an issue related to the usage of Filament v3 and Breezy v2 in our project. It has come to our attention that when the panel incorporates Tenancy, the my-profile page fails to function as expected. This is because the application expects a tenant id.

**Steps to Reproduce:**
1. Install Filament v3 and Breezy v2 in the project.
2. Configure the panel to include Tenancy.
3. Navigate to the my-profile page.

**Expected Behavior:**
The my-profile page should function correctly, regardless of the Tenancy configuration.

**Actual Behavior:**
Upon accessing the my-profile page with Tenancy enabled, the page does not work as intended, leading to an error.

**Screenshot:**
<img width="1440" alt="Scherm­afbeelding 2023-07-21 om 23 21 50" src="https://github.com/jeffgreco13/filament-breezy/assets/35234103/a3d346b3-ff60-4d85-aa69-501478e219af">

Best regards,
Tygo Egmond

**Comment by mstfkhazaal** [comment]
I have same problem

**Comment by mstfkhazaal** [comment]
> Hello,
> 
> I hope this message finds you well. I am writing to report an issue related to the usage of Filament v3 and Breezy v2 in our project. It has come to our attention that when the panel incorporates Tenancy, the my-profile page fails to function as expected. This is because the application expects a tenant id.
> 
> **Steps to Reproduce:**
> 
> 1. Install Filament v3 and Breezy v2 in the project.
> 2. Configure the panel to include Tenancy.
> 3. Navigate to the my-profile page.
> 
> **Expected Behavior:** The my-profile page should function correctly, regardless of the Tenancy configuration.
> 
> **Actual Behavior:** Upon accessing the my-profile page with Tenancy enabled, the page does not work as intended, leading to an error.
> 
> **Screenshot:** <img alt="Scherm­afbeelding 2023-07-21 om 23 21 50" width="1440" src="https://user-images.githubusercontent.com/35234103/255286200-a3d346b3-ff60-4d85-aa69-501478e219af.png">
> 
> Best regards, Tygo Egmond

I fix it https://github.com/jeffgreco13/filament-breezy/pull/189

**Comment by aeq-dev** [comment]
+1

**Comment by jeffgreco13** [comment]
Merged in 2.1.1
