### ISSUE TITLE
TwoFactorPage SimplePage dont exist v2.0.0-beta2

### ISSUE THREAD

**Issue by sebastiancx** [jeffgreco13/filament-breezy#182]
Hi!
I am trying out Filament 3 and I installed your released version v2.0.0-beta2 which has been optimized for Filament 3.

Unfortunately this release seems to be buggy, because the SimplePage, that is used inside of
```php
class TwoFactorPage extends SimplePage
```
is no longer supported since Filament 3.
It was different in your previous release Beta1 and now again in Beta2. What was the issue or was that a mistake?

**Comment by jeffgreco13** [comment]
Which release of Filament v3 are you using?
In alpha, there was a CardPage available but that changed to SimplePage in beta.

**Comment by sebastiancx** [comment]
Oh right, I saw this morning that I was using the alpha. My mistake, sorry.
