### ISSUE TITLE
Filament v3 support?

### ISSUE THREAD

**Issue by faizananwerali** [jeffgreco13/filament-breezy#184]
Filament v3 has been released. Will you be supporting it?

**Comment by jeffgreco13** [comment]
Release coming today!
The only thing that needs work is Tenancy support because there's an issue with conflicting middleware.

**Comment by ilkermutlu** [comment]
Looking forward to it to be able to upgrade to Filament v3!

**Comment by mgkyawzayya** [comment]
I don't see register page documentation for filament v3

**Comment by jeffgreco13** [comment]
@mgkyawzayya registration is no longer in Breezy because it's included with Filament v3. See the Filament v3 docs to enable this

**Comment by sheepbild** [comment]
@jeffgreco13 I can't find how to activate registration on filamentphp v3 docs ; do you know where it is explained ?

**Comment by faizananwerali** [comment]
> @mgkyawzayya registration is no longer in Breezy because it's included with Filament v3. See the Filament v3 docs to enable this

[https://filamentphp.com/docs/3.x/panels/users#authentication-features](https://filamentphp.com/docs/3.x/panels/users#authentication-features)

```php
use Filament\Panel;
 
public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->login()
        ->registration()
        ->passwordReset()
        ->emailVerification()
        ->profile();
}
```

**Comment by faizananwerali** [comment]
> I don't see register page documentation for filament v3

It is now included in Filament v3 [Authentication features](https://filamentphp.com/docs/3.x/panels/users#authentication-features)

```php
use Filament\Panel;
 
public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->login()
        ->registration()
        ->passwordReset()
        ->emailVerification()
        ->profile();
}
```
