### ISSUE TITLE
Possible Bug: User avatar doesn't show in navbar - v3

### ISSUE THREAD

**Issue by andyholmeswonderful** [jeffgreco13/filament-breezy#187]
I'm a new Filament user, and I'm trying out V3. I've installed everything correctly as a new project, but I've noticed a few things.

Once an avatar has successfully uploaded and is stored in the database, it doesn't show in the menu bar (where the user's initials would originally be). The code for a background-image is there, but it seems to be loading without the `storage` prefix.

Is there some steps that I'm missing? 

<img width="446" alt="Screenshot 2023-08-02 at 11 46 12" src="https://github.com/jeffgreco13/filament-breezy/assets/88321043/a39b241e-6180-4996-86b2-262d2c1472d9">

<img width="254" alt="Screenshot 2023-08-02 at 11 46 20" src="https://github.com/jeffgreco13/filament-breezy/assets/88321043/f255c7e1-20c0-4712-8681-37ca8cd14da4">

<img width="435" alt="Screenshot 2023-08-02 at 11 53 04" src="https://github.com/jeffgreco13/filament-breezy/assets/88321043/ad781196-0b49-497e-8bf7-f4071e547cba">

And then when I add `/storage/` in dev tools:

<img width="435" alt="Screenshot 2023-08-02 at 11 53 21" src="https://github.com/jeffgreco13/filament-breezy/assets/88321043/91838b65-0a15-4ad3-95e3-68c95da3dd7c">

<img width="246" alt="Screenshot 2023-08-02 at 11 53 25" src="https://github.com/jeffgreco13/filament-breezy/assets/88321043/3628ebe1-19aa-4c6b-91a1-44be1e7b69d0">

**Comment by andyholmeswonderful** [comment]
I fixed it by doing this in my User model:

```
    public function getFilamentAvatarUrl(): ?string
    {
        return asset('storage/'.$this->avatar_url);
    }
```

**Comment by jeffgreco13** [comment]
@andyholmeswonderful correct. After enabling avatars in Breezy, you follow the Filament v3 docs for using avatars in the panel.

**Comment by andyholmeswonderful** [comment]
@jeffgreco13 Thanks for confirming, sorry for opening the issue, I hadn't seen that part of Filament's docs

**Comment by githubenrico** [comment]
I didn't understand how you saved it in the database :-(

**Comment by andyholmeswonderful** [comment]
> I didn't understand how you saved it in the database :-(

Add the `avatar_url` to your user migration as a string, add it to the fillable fields on the User model, and then do what I did above if you need to.
