### ISSUE TITLE
BadMethodCallException    Method Filament\Panel::getDomains does not exist.  Filament V3

### ISSUE THREAD

**Issue by zimamarrois** [jeffgreco13/filament-breezy#217]
`
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   BadMethodCallException

  Method Filament\Panel::getDomains does not exist.

  at vendor\filament\support\src\Concerns\Macroable.php:72
     68▕     {
     69▕         $macro = static::getMacro($method);
     70▕
     71▕         if ($macro === null) {
  ➜  72▕             throw new BadMethodCallException(sprintf(
     73▕                 'Method %s::%s does not exist.',
     74▕                 static::class,
     75▕                 $method,
     76▕             ));

  i   Bad Method Call: Did you mean Filament\Panel::getDomain() ?

  1   vendor\jeffgreco13\filament-breezy\routes\web.php:10
      Filament\Support\Components\Component::__call("getDomains", [])

  2   vendor\laravel\framework\src\Illuminate\Routing\Router.php:502
      Illuminate\Support\ServiceProvider::{closure}(Object(Illuminate\Routing\Router))

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`

**Comment by LucVK** [comment]
Upgrading to latest filament/filament version (v3.0.27) solved this problem

**Comment by anoshiri** [comment]
Changing this in composer.json file solved the problem for me

"filament/actions": "^3.0",
"filament/filament": "^3.0",
"filament/forms": "^3.0",
"filament/notifications": "^3.0",
"filament/tables": "^3.0",
