### ISSUE TITLE
Override My Profile components

### ISSUE THREAD

**Issue by LucVK** [jeffgreco13/filament-breezy#219]
I tried to override the 'personal_info' profile component with my own (as my user objects have first and lastname fields).
I followed the documentation and this seems to work. I get the new fields (first_name and last_name) displayed.
When I try to save changes, I get a validation error stating that the name field cannot be empty, and the original view (with only a name field is shown).

After a little debugging I discovered the following:
1. The submit button on the custom view triggers the submit method in the original component, making the validation fail as there is no name field in the form.

The reason is that the original personal_info component is always registered in the BreezyCore class (line 98). When I comment out this line and register my custom component (using Livewire::component) in the panel provider, everything works as expected.

My suggested solution is to adapt the BreezyCore class and test if components have been overridden. (something like)

if (array_key_exists('personal_info', $this->getRegisteredMyProfileComponents())
{
   Livewire::comonent('the custom component');
}
else
{
   do exisiting logic
}

Br,
Luc

**Comment by jeffgreco13** [comment]
Can you share your code implementing `BreezyCore::make()` and the code in your custom component?
I will try to recreate this issue.

Your custom component, if it is in the default Livewire folder, should not need to be registered in the Breezy plugin. Your app should autodiscover the new component.

Please also do me this favor:

1. Locate vendor/jeffgreco13/filament-breezy/src/Pages/MyProfilePage.php: 41 `getRegisteredMyProfileComponents()`
2. Within this method, replace with the following:
```php
    public function getRegisteredMyProfileComponents(): array
    {
        dd(filament('filament-breezy')->getRegisteredMyProfileComponents());
        // return filament('filament-breezy')->getRegisteredMyProfileComponents();
    }
```

Send me a screenshot of the output when you visit the MyProfile page. It should return an array of components that have been registered for this page. I will inspect possible issues.

**Comment by LucVK** [comment]
![image](https://github.com/jeffgreco13/filament-breezy/assets/350118/adf911a9-005c-4eb0-b855-a111fa1a8a28)

**Comment by LucVK** [comment]
I retested my application after looking at your example code in #207 
It looks like the problem only occurs when the replacing livewire component is also named 'PersonalInfo'. Once I renamed it to 'MyPersonalInfo' the problems are solved.

**Comment by 0proboy0** [comment]
@LucVK After I reamed it, I got an error:
![image](https://github.com/jeffgreco13/filament-breezy/assets/14108109/7f78a72b-34ff-4734-91d3-fd51da102c95)
Have you had it as well? how did you fixed it?

![image](https://github.com/jeffgreco13/filament-breezy/assets/14108109/8890aa46-fb0f-4169-8a8e-7584afa89065)

**CustomPersonalInfo.php**
```php
<?php

namespace App\Livewire\Overwritten\Filament\FilamentBreezy;

use App\Models\User;
use Jeffgreco13\FilamentBreezy\Livewire\PersonalInfo;
use Filament\Forms;

class CustomPersonalInfo extends PersonalInfo
{
    protected string $view = "livewire.Overwritten.Filament.FilamentBreezy.custom-personal-info";

    public array $only = ['name', 'email', 'phone'];

    protected function getProfileFormSchema()
    {
        $name = Forms\Components\TextInput::make('name')
            ->required()
            ->label(__('filament-breezy::default.fields.name'));
        $email = Forms\Components\TextInput::make('email')
            ->required()
            ->email()
            ->unique($this->userClass, ignorable: $this->user)
            ->label(__('filament-breezy::default.fields.email'));
        $phone = Forms\Components\TextInput::make('phone')
            ->required()
            ->unique(table: User::class, ignoreRecord: true)
            ->rules(['numeric', 'digits:10'])
            ->label(__('filament-panels::pages/auth/edit-profile.form.phone.label'));

        if ($this->hasAvatars) {
            return [
                filament('filament-breezy')->getAvatarUploadComponent(),
                Forms\Components\Group::make([
                    $name,
                    $email,
                    $phone
                ])->columnSpan(2),
            ];
        } else {
            return [
                Forms\Components\Group::make([
                    $name,
                    $email,
                    $phone
                ])->columnSpan(3)
            ];
        }
    }
}

```

**Comment by 0proboy0** [comment]
> @LucVK After I reamed it, I got an error **after I click on Update button**: ![image](https://user-images.githubusercontent.com/14108109/262657465-7f78a72b-34ff-4734-91d3-fd51da102c95.png) Have you had it as well? how did you fixed it?
> 
> ![image](https://user-images.githubusercontent.com/14108109/262657687-8890aa46-fb0f-4169-8a8e-7584afa89065.png)
> 
> **CustomPersonalInfo.php**
> 
> ```
> <?php
> 
> namespace App\Livewire\Overwritten\Filament\FilamentBreezy;
> 
> use App\Models\User;
> use Jeffgreco13\FilamentBreezy\Livewire\PersonalInfo;
> use Filament\Forms;
> 
> class CustomPersonalInfo extends PersonalInfo
> {
>     protected string $view = "livewire.Overwritten.Filament.FilamentBreezy.custom-personal-info";
> 
>     public array $only = ['name', 'email', 'phone'];
> 
>     protected function getProfileFormSchema()
>     {
>         $name = Forms\Components\TextInput::make('name')
>             ->required()
>             ->label(__('filament-breezy::default.fields.name'));
>         $email = Forms\Components\TextInput::make('email')
>             ->required()
>             ->email()
>             ->unique($this->userClass, ignorable: $this->user)
>             ->label(__('filament-breezy::default.fields.email'));
>         $phone = Forms\Components\TextInput::make('phone')
>             ->required()
>             ->unique(table: User::class, ignoreRecord: true)
>             ->rules(['numeric', 'digits:10'])
>             ->label(__('filament-panels::pages/auth/edit-profile.form.phone.label'));
> 
>         if ($this->hasAvatars) {
>             return [
>                 filament('filament-breezy')->getAvatarUploadComponent(),
>                 Forms\Components\Group::make([
>                     $name,
>                     $email,
>                     $phone
>                 ])->columnSpan(2),
>             ];
>         } else {
>             return [
>                 Forms\Components\Group::make([
>                     $name,
>                     $email,
>                     $phone
>                 ])->columnSpan(3)
>             ];
>         }
>     }
> }
> ```

The fix for that is to put your component exactly in `"App\Livewire"`, for me, it was in: `"App\Livewire\Overwritten\Filament\FilamentBreezy"` and that causes the problem.
@jeffgreco13 is this considered as a bug?
I should ention that the error happens only when I click on the Update button, otherwise the component worked without any problem.

So the issues are:
1. the custom PersonalInfo.php class can't be named as the original one (PersonalInfo).
2. the custom component should be exactly at `"App\Livewire"` (no sub folders).

**Comment by shanerbaner82** [comment]
I am not sure if this issue is related or a separate bug, but I am adding a component to my profile area (author bio and hopefully links) and when I submit I am getting the following error: 
```
Unable to find component: [bio]
```

If you feel I should submit a different issue, please inform, but I htink this is closely related to the problems you are currently facing.


<img width="1363" alt="Screenshot 2023-08-23 at 9 06 39 AM" src="https://github.com/jeffgreco13/filament-breezy/assets/5580860/46990d2a-3c49-4314-84d1-259b6260bf19">
<img width="1267" alt="Screenshot 2023-08-23 at 9 06 32 AM" src="https://github.com/jeffgreco13/filament-breezy/assets/5580860/5a63d906-b3a1-4a08-b8d0-9b9d16a7cd06">
<img width="943" alt="Screenshot 2023-08-23 at 9 06 23 AM" src="https://github.com/jeffgreco13/filament-breezy/assets/5580860/ce7458f6-0b53-45c9-a895-13c639498b88">
<img width="729" alt="Screenshot 2023-08-23 at 9 06 15 AM" src="https://github.com/jeffgreco13/filament-breezy/assets/5580860/5281dc05-d9d8-454e-9050-9920c2574798">
<img width="809" alt="Screenshot 2023-08-23 at 9 06 00 AM" src="https://github.com/jeffgreco13/filament-breezy/assets/5580860/622d43b2-80bf-47c5-aa14-218df6c16d27">

**Comment by LucVK** [comment]
@shanerbaner82 Try to put i directly in App\Livewire (I think this should work)
You can use php artisan livewire:move profile.bio my-profile-bio

In the mean time lets wait for @jeffgreco13 for a final solution

Br,
Luc

**Comment by boris-glumpler** [comment]
I registered my profile component as Livewire component in a service provider:

```php
Livewire::component('my-breezy-personal-info', App\Filament\Breezy\PersonalInfo::class);
``` 

And then overrode the `getName` method in `App\Filament\Breezy\PersonalInfo::class`:

```php
public function getName(): string
{
    return 'my-breezy-personal-info';
}
```

Last step was to set the component in the panel config:

```php
->myProfileComponents([
  'personal_info'  => App\Filament\Breezy\PersonalInfo::class,
])
```

You can't use `my-breezy-personal-info` here, btw. as you're overriding an existing component.
