### ISSUE TITLE
Hover-over highlight effect missing in v2?

### ISSUE THREAD

**Issue by bhattji** [jeffgreco13/filament-breezy#223]
In version 1.x when I hover-over the profile name button, it use to get highlighted, by default
<img width="881" alt="highlighted-button" src="https://github.com/jeffgreco13/filament-breezy/assets/2518119/749dc3ef-ad04-4ddc-9c89-149823c8767a">
. 

How do I do that in v2.x?

**Comment by jeffgreco13** [comment]
This is not a Breezy issue. Please ask questions like this in the Filament Discord channel, as this is unrelated to this repo.
