### ISSUE TITLE
Profile page - subheading - translation missing

### ISSUE THREAD

**Issue by LucVK** [jeffgreco13/filament-breezy#224]
The translation for the subheading of the profile page is missing.

![image](https://github.com/jeffgreco13/filament-breezy/assets/350118/ff8cea37-c0eb-4b95-b4f4-a623704eb6dd)

**Comment by jeffgreco13** [comment]
Please provide a PR with the updated translation for path `default.profile.subheading`.
Breezy has been translated in 22 languages by the community, I only know 3 :)
