### ISSUE TITLE
[Question] Where is filament-breezy config?

### ISSUE THREAD

**Issue by 0proboy0** [jeffgreco13/filament-breezy#229]
![image](https://github.com/jeffgreco13/filament-breezy/assets/14108109/f38d365f-d516-4088-9ccf-24de7b78b75a)

filament-breezy config is mentioned here but I really can't find it anywhere, I want to edit the number of seconds.

**Comment by 0proboy0** [comment]
+ I think the default is not 300s which is 5min, I waited more than that but I still can run the action without asking for the password (it did asked for password the first time).
Please check that too.

**Comment by 0proboy0** [comment]
Found out that the seconds should be edited here:
![image](https://github.com/jeffgreco13/filament-breezy/assets/14108109/353c6a52-7052-48dc-9a1d-8627d5f44e3d)
Because of this:
![image](https://github.com/jeffgreco13/filament-breezy/assets/14108109/38ef69bf-d8dc-4e45-8b92-46ec61eef8ae)
So maybe the documentation is old?

**Comment by jeffgreco13** [comment]
You are correct, I missed this in the upgrade. I'll send a PR with the next release.
