### ISSUE TITLE
Invalid Code

### ISSUE THREAD

**Issue by nlvrendell** [jeffgreco13/filament-breezy#254]
I dunno why, but I cannot confirm and finish the 2FA, the code given by google authenticator does not match up. Anything that I need to setup? I just followed the instruction.

Code added at AdminPanelProvider
```
`->plugin(
                BreezyCore::make()
                    ->myProfile(
                        shouldRegisterUserMenu: true, // Sets the 'account' link in the panel User Menu (default = true)
                        shouldRegisterNavigation: false, // Adds a main navigation item for the My Profile page (default = false)
                        hasAvatars: false, // Enables the avatar upload form component (default = false)
                        slug: 'my-profile' // Sets the slug for the profile page (default = 'my-profile')
                    )
                    ->enableTwoFactorAuthentication(
                        force: false, // force the user to enable 2FA before they can use the application (default = false)
                        // action: CustomTwoFactorPage::class // optionally, use a custom 2FA page
                    )
            );
```
 
 Also Implemented the TwoFactorAuthenticatable at the model. 
![image](https://github.com/jeffgreco13/filament-breezy/assets/124220382/cb05a38a-c830-4196-91a5-d4b084a16cd1)

Issue:
![image](https://github.com/jeffgreco13/filament-breezy/assets/124220382/001d0e78-7687-49a7-9c00-161c2cfcb32a)

**Comment by nlvrendell** [comment]
Sorry. Already solved this issue. The timezone of my system and the timezone of my phone should be the same.

**Comment by gosheto** [comment]
@nlvrendell 
Hello,
I also have this issue and cannot confirm and finish the 2FA.

Where you change timezone - on server (Linux/Windows... OS), php version php.ini or Laravel conf/app.php?
My server timezone is "Europe/Sofia", php.ini - timezone is not set, Laravel conf/app.php is set to UTC.
If I set Laravel conf/app.php to "Europe/Sofia", application start working with wrong time for my timezone - +3:00.
With timezone set to UTC in Laravel application work with correct time for my timezone "Europe/Sofia".
My phone is set to "Europe/Sofia".

Thank you in advance!
