### ISSUE TITLE
Update Password Notification message

### ISSUE THREAD

**Issue by nlvrendell** [jeffgreco13/filament-breezy#256]
Is their anyway to manually update this message? I think the default message should not be like this. Thanks

![image](https://github.com/jeffgreco13/filament-breezy/assets/124220382/1ca0df78-9bfc-4bc8-9580-f4576a70f87a)

From:  ->title('filament-breezy::default.profile.password.notify')
To:  ->title(__('filament-breezy::default.profile.password.notify'))
![image](https://github.com/jeffgreco13/filament-breezy/assets/124220382/f2379db0-6eb4-4f82-a6f1-73f0d3566f33)

**Comment by jeffgreco13** [comment]
Merged
