### ISSUE TITLE
md5(): Argument #1 ($string) must be of type string, int given

### ISSUE THREAD

**Issue by bladerunner2021** [jeffgreco13/filament-breezy#266]
After composer update
got md5(): Argument #1 ($string) must be of type string, int given
Disabling plugin load everything works fine

**Comment by jeffgreco13** [comment]
@bladerunner2021 can you provide more information please? A screenshot or perhaps a Flare.io link?

**Comment by jeffgreco13** [comment]
Please update to 2.1.5

**Comment by bladerunner2021** [comment]
I got the error just after entered the authenticator code. It is able to recognize if the code is correct or not.
<img width="1370" alt="Screenshot 2023-10-18 alle 20 06 16" src="https://github.com/jeffgreco13/filament-breezy/assets/81435970/8814e666-5907-4b1d-a363-7732720cdaa6">
