### ISSUE TITLE
Error when updating to 2.1.14

### ISSUE THREAD

**Issue by bomshteyn** [jeffgreco13/filament-breezy#267]
Am getting the following errors when updating to the newest release.

-  `Typed property Jeffgreco13\FilamentBreezy\BreezyCore::$twoFactorAuthentication must not be accessed before initialization`
-  ` Typed property Jeffgreco13\FilamentBreezy\BreezyCore::$twoFactorRouteAction must not be accessed before initialization`

**Comment by jeffgreco13** [comment]
Please update to 2.1.5
