### ISSUE TITLE
shouldRegisterUserMenu true not working

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [jeffgreco13/filament-breezy#288]
Hello,

It seems the _shouldRegisterUserMenu: true_ is not resulting in the account link being shown in the user panel.

I use the following code:

```
->plugin(BreezyCore::make()
                ->myProfile(
                    shouldRegisterUserMenu: true, // Sets the 'account' link in the panel User Menu (default = true)
                    shouldRegisterNavigation: false, // Adds a main navigation item for the My Profile page (default = false)
                    hasAvatars: false, // Enables the avatar upload form component (default = false)
                    slug: 'my-profile', // Sets the slug for the profile page (default = 'my-profile')
                )
                ->enableTwoFactorAuthentication(
                    force: false, // force the user to enable 2FA before they can use the application (default = false)
                )
            )
```

But it is not resulting in anything:

<img width="240" alt="image" src="https://github.com/jeffgreco13/filament-breezy/assets/25418904/c40dd045-653b-4f91-9358-f48239ff2c85">

Any suggestions on what might be going wrong?

**Comment by retifex** [comment]
I wondered the same thing at first.
Answer: The name that you see is the link to your account. If you click on "Adriaan", you will be taken to your profile page.

**Comment by skyjebus** [comment]
> I wondered the same thing at first.
> 
> Answer: The name that you see is the link to your account. If you click on "Adriaan", you will be taken to your profile page.

This is the answer

**Comment by jeffgreco13** [comment]
Answered by retifex
