### ISSUE TITLE
German translation needs update

### ISSUE THREAD

**Issue by retifex** [jeffgreco13/filament-breezy#289]
The German translation is incomplete. For example, the string "profile/subheading" is missing. I would like to update it.

Please help a newbie:

1. which language file is the reference? Is "en" the reference?

2. also, the strings between "en" and "de" differ significantly. Some strings are missing in "de", others exist in "de" but are missing in "en", for example "login/username_or_email". Should the "de" file be adapted so that exactly the same strings exist in "de" as in "en", i.e. should the "additional" strings in "de" be deleted?

3. is it okay to customise only one language file? Or do all language files always have to be adapted at the same time, as @majdcodes did recently?

Thank you very much!

**Comment by jeffgreco13** [comment]
Hi @retifex sorry for the late response here. In Breezy v2, there are new strings that were not translated so I have been asking the community to help by submitted PRs with the updated strings in each language.

That is why some strings might be missing in "de". If you can submit a PR with these new strings, I will merge them in. To answer your question, if you copy the same array structure from "en" to "de", leave the keys the same and simply change the values to the proper de translation.

You can modify 1 or as many languages as you know.
