### ISSUE TITLE
Is it possible to disable the PersonalInfo and UpdatePassword components?

### ISSUE THREAD

**Issue by sh4msi** [jeffgreco13/filament-breezy#291]
Hello,
I have a question regarding disabling the PersonalInfo and UpdatePassword components. Is there a way to deactivate these two components similar to the other components?

If there is no optional solution available, would you be interested in me sending a Pull Request (PR) for implementing this change?

**Comment by sh4msi** [comment]
@jeffgreco13

**Comment by caendesilva** [comment]
I'm also surprised that this doesn't seem to be possible in the v3 version. My app only uses OAuth Socialite authentication so there are no passwords, and it's just confusing to have the form.

Should be fairly easy to add something to these lines?

https://github.com/jeffgreco13/filament-breezy/blob/82abe61e778dbbd2e0c8081516336663a7dced2f/src/BreezyCore.php#L100-L103

**Comment by caendesilva** [comment]
Feature to handle this will be available in the next release. To use it, chain the `withoutMyProfileComponents` to your Filament plugin registration

```php
->plugin(
    BreezyCore::make()
        ->withoutMyProfileComponents([
            'update_password'
        ])
);
```
