### ISSUE TITLE
Totally lost on tweaking registration_component_path. How do you do it in v2?

### ISSUE THREAD

**Issue by epertinez** [jeffgreco13/filament-breezy#294]
I had this hack that worked for me.
In my app, users come from different DB tables. They don't have a User profile yet, but once they register, they will be able to do things depending on what table are they in. Are they Customers? Are they Providers?...

The way I did it in v1 is straight forward:
In confib/filament-breezy.php:
    "registration_component_path" => \App\Http\Livewire\Registerv3::class, 

And then, my livewire component modified FilamentBreezyRegister

```php
namespace App\Http\Livewire;

use Filament\Facades\Filament;
use Filament\Forms;
use Illuminate\Auth\Events\Registered;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Hash;
use JeffGreco13\FilamentBreezy\FilamentBreezy;
use Livewire\Component;

use App\Models\SomeModel;


use JeffGreco13\FilamentBreezy\Http\Livewire\Auth\Register as FilamentBreezyRegister;


class Registerv3 extends FilamentBreezyRegister
{

        // Override the getFormSchema method and merge the default fields then add your own.
        protected function getFormSchema(): array
        {
        // DO NOT NEED THE NAME AS ALL USERS INFO ARE ALREADY IN MY SYSTEM AND ALL OF THEM HAVE A NAME
        return [
            Forms\Components\TextInput::make('email')
                ->label(__('filament-breezy::default.fields.email'))
                ->required()
                ->email()
                ->unique(table: config('filament-breezy.user_model')),
            Forms\Components\TextInput::make('password')
                ->label(__('filament-breezy::default.fields.password'))
                ->required()
                ->password()
                ->rules(app(FilamentBreezy::class)->getPasswordRules()),
            Forms\Components\TextInput::make('password_confirm')
                ->label(__('filament-breezy::default.fields.password_confirm'))
                ->required()
                ->password()
                ->same('password'),
        ];
    
    
    }
        // Use this method to modify the preparedData before the register() method is called.
    protected function prepareModelData($data): array
    {
        // If email is in some model, I retrieve the data from the model.
        $possibleUSER=SomeModel::where('email','=',$data['email']);
        if ($possibleUSER->count()) {
            $preparedData = [
                'name' => $possibleUSER->first()->some_name_field,
                'email' => $data['email'],
                'password' => Hash::make($data['password']),
                'role' => 'Some role',
            ];
            return $preparedData;
        }
        // If the user is not in the system I just return nothing as data.
        return [];
    }
    
    // Optionally, you can override the entire register() method to customize exactly what happens at registration
    public function register()
    {
        $preparedData = $this->prepareModelData($this->form->getState());
        if (!empty($preparedData)) {
            $user = config('filament-breezy.user_model')::create($preparedData);
            $user->assignRole($preparedData['role']);
            event(new Registered($user));
            Filament::auth()->login($user, true);
            return redirect()->to(config('filament-breezy.registration_redirect_url'));
        }
        return redirect()->to(config('filament-breezy.registration_redirect_url'));
 
    }




}

```
This code worked well.
Now, with v2, i am not able to make my Registerv3 function to work.

So, the question is:

a) Is there anyway in v2 to change registration component?
b) Can I install v1 with filament v3?
c) Should I simply modify any other filament v3 page instead of your plugin?

I am out of clues, so any tip will be very appreciated.

Regards

**Comment by chrissy-dev** [comment]
@epertinez I'm also having this issue. Needing some clarity.

**Comment by epertinez** [comment]
I ended up not using JeffGreco13\FilamentBreezy\FilamentBreezy at all.
What I did is...
a) Register a Hook to auth.login to welcome newcomers and ask them to request the password as lost even if it is the first time they are coming...
class AppPanelProvider extends PanelProvider
{
    public function boot(): void
    { FilamentView::registerRenderHook(
        'panels::auth.login.form.after',
        fn (): View => view('login-explanation'),
        );
    }

(use resources/views/login-explanation.blade.php to add some message after login form).

b) Overwrite PasswordReset class and call it form panel in AppPanelProvider class...

use App\Http\Livewire\RequestPasswordResetMyClass;

public function panel(Panel $panel): Panel
    {
        return $panel
            /// Some modificators
            ->passwordReset(RequestPasswordResetMyClass::class)
            /// many more modificators

...

Then I created a class that takes the email, checks if it is a valid candidate and if it is CREATES the user and calls normal parent class to keep doing its thing once the user has already been created.

<?php

namespace App\Http\Livewire;

use Filament\Pages\Auth\PasswordReset\RequestPasswordReset as BaseRequestPasswordReset;


class RequestPasswordResetMyClass extends BaseRequestPasswordReset
{

    public function checkOrCreate($email) {
            // invented function (maybe it should be private, my fault) that looks for the email in authorized database
            if (i have found the email in authorized datablase) {
            $user=new User;
            $user->name= something from the ddbb;
            $user->email=$email;
            $user->password=\Hash::make(random_bytes(20)); // Some invented and soon forgotted password so I can create the user
            $user->assignRole('Some role depending on the place I found the email');
            $user->create();
           }
            return;
         }
    public function request(): void
    {  
        $email=$this->data['email'];
        $this->checkOrCreate($email);

       // From here on, if the user email existed in my DDBB it is created. If not... no problem... normal behaviour of the class will give proper errors.
       // I call parent method and continue from there.
        parent::request();
    }

    
    
}

**Comment by jeffgreco13** [comment]
Hi. Yes, since Breezy v2 and Filament v3, Filament now provides registration, password reset and email verification in the core. Any customizations you have made to any of these pages in Breezy v1 will need to be refactored to extend the core features.

See official docs here: https://filamentphp.com/docs/3.x/panels/users#authentication-features

**Comment by chrissy-dev** [comment]
Brilliant, thank you both for the clarity on this. @jeffgreco13 I'm happy to add something in the docs/README about this change.

**Comment by jeffgreco13** [comment]
@chrissy-dev I would accept that PR! Thank you for your contribution.

**Comment by chrissy-dev** [comment]
@jeffgreco13 It's in #310
