### ISSUE TITLE
How do I know if filament-breezy is working?

### ISSUE THREAD

**Issue by epertinez** [jeffgreco13/filament-breezy#295]
Hi,
I have followed your instructions to install your plugin in my system, but I am not sure it is working.

a) I added it to both AdminPanelProvider and AppPanelProvider.
             ->plugins([
                BreezyCore::make()->myProfileComponents([ 'update_password' => Registerv3::class]),
                FilamentSpatieRolesPermissionsPlugin::make(),
                ])
b)   Plugins get loaded as if I put some breakpoints in BreezyCore I can see in debug mode that the class is being created.

c) Yet, if I go to http://127.0.0.1:8000/myApp/password-reset/request

none of the break points I put in my debugger seem to work.
I put break points in mount() and form($form) both in my own Registerv3 class and 
vendor/jeffgreco13/filament-breezy/src/Livewire/UpdatePassword.php

but none of them halts the run... so I understand none of them is being gone through....

In fact, when the program pauses in my breakpoint in the boot function in BreezyCore... it looks like $panel variables are routed  to Filament pages and not the plugin ones...

loginRouteAction "Filament\Pages\Auth\Login"
 registrationRouteAction "Filament\Pages\Auth\Register"
requestPasswordResetRouteAction "Filament\Pages\Auth\PasswordReset\RequestPasswordReset"
resetPasswordRouteAction "Filament\Pages\Auth\PasswordReset\ResetPassword"

Any clue? What am I doing wrong?

**Comment by jeffgreco13** [comment]
Hi @epertinez if you check the code for the `myProfileComponents` method, any breakpoints in custom components would only take effect on the MyProfile page. The page you listed in point (b) is a password reset request page.

Consider taking this request to the Discord chat!

**Comment by epertinez** [comment]
Thank you. I ended up with a very different approach as stated in another thread of mine.
