### ISSUE TITLE
language files "subheading" missing in lang/de

### ISSUE THREAD

**Issue by andreasotto** [jeffgreco13/filament-breezy#296]
The key profile.subheading is missing in lang/de/default.php displaying wrong (english) subheading text in profile page.

**Comment by jeffgreco13** [comment]
Please submit a PR if you know the proper translation.

**Comment by phh** [comment]
Guess this was fixed here?

https://github.com/jeffgreco13/filament-breezy/pull/317/files

**Comment by jeffgreco13** [comment]
@phh I believe so! Will close
