### ISSUE TITLE
Can't find avatar url in blade

### ISSUE THREAD

**Issue by MechanicalEclipse** [jeffgreco13/filament-breezy#300]
Hi, love filament breezy, but i'm having this problem with the avatar upload.
I have implemented and followed the documentation

Panel provider:
```
BreezyCore::make()
                ->myProfile(
                    shouldRegisterUserMenu: true, // Sets the 'account' link in the panel User Menu (default = true)
                    shouldRegisterNavigation: false, // Adds a main navigation item for the My Profile page (default = false)
                    hasAvatars: true, // Enables the avatar upload form component (default = false)
                    slug: 'profilo' // Sets the slug for the profile page (default = 'my-profile')
                )
``` 

User model:
```
public function getFilamentAvatarUrl(): ?string
    {
        return $this->avatar_url ? Storage::url($this->avatar_url) : null ;
    }
```
and added the migration 
![image](https://github.com/jeffgreco13/filament-breezy/assets/44363714/b9c01b2c-9556-4729-91c4-cc7b297c5745)

When i upload an avatar it uploads correctly, but when i'm on the web page it throws this errors:
![image](https://github.com/jeffgreco13/filament-breezy/assets/44363714/e42984e0-8d50-458f-a0bd-af2f88fcb606)
and i see this:
![Screenshot 2023-12-11 123430](https://github.com/jeffgreco13/filament-breezy/assets/44363714/e8257da3-08f1-4279-a56a-6f22c9277ef9)

What can cause this? Did i do something wrong?

**Comment by jeffgreco13** [comment]
This must be an issue with your URLs, storage path, or have you set up your symlink with `php artisan storage:link`?

Closing the issue as this is not Breezy related.
