### ISSUE TITLE
In roles page (for each role) takes too much time to modify permissions

### ISSUE THREAD

**Issue by ehs4nm** [jeffgreco13/filament-breezy#32]
Hi thanks for the good package you provide to community. 
When i have many models like more than 10, In roles page (for each role) takes too much time to modify permissions. As i see in network request, the response for each modification takes a lot of resources and heavy in size (+600kb).
I'm not sure how to make it faster.

**Comment by jeffgreco13** [comment]
Hi @ehs4nm Are you referring to Filament Shield? There is no Roles page in this package.

**Comment by ehs4nm** [comment]
Man!! You right. why i didn't notice. I'm sorry for the noise.
