### ISSUE TITLE
Password check fail on multiple panels/guards

### ISSUE THREAD

**Issue by ace18** [jeffgreco13/filament-breezy#321]
## Summary
I'm using multiple panels in a multi tenancy installation with a different guard for each, the panels' `authGuard` is set up correctly, but it seems that the livewire update route still uses the default one, `web`.
The password rule could be replaced with `rule("current_password:" . filament('filament-breezy')->getCurrentPanel()->getAuthGuard())`

## Installed versions
- Filament v3.2.2
- Breezy v2.2.5
- stancl/tenancy v3.7.2

**Comment by metagenes** [comment]
I'm experiencing a similar issue in a multi-panel setup. I'm using separate guards for each panel, and even tried explicitly calling `authGuard('my_guard')`, but that didn’t resolve the password verification failure during Livewire updates. It seems the route still defaults to the `web` guard behind the scenes.

Curious if there's a clean workaround or override for forcing the correct guard context in Livewire's validation rule. Any insights or best practices would be appreciated!
