### ISSUE TITLE
Missing CI / Github Actions

### ISSUE THREAD

**Issue by phh** [jeffgreco13/filament-breezy#323]
Hi there,

I think this project could really benefit of adding Github actions for workflows like code formatting, phpstan and tests.

Since this package is generated from the [spatie/package-skeleton-laravel](https://github.com/spatie/package-skeleton-laravel) it should be pretty strait forward to just include actions as such.

If you want to I can make an attempt at this, opening a PR.

**Comment by jeffgreco13** [comment]
I would appreciate a PR! Thank you @phh
