### ISSUE TITLE
Not a bug but a question (or feature request): How to backup the permissions so after refresh it doesn't go a way

### ISSUE THREAD

**Issue by ehs4nm** [jeffgreco13/filament-breezy#33]
I may not been clear in my question.
Each time refreshing database with `migrate:refresh` i need to do all permissions again. As all permissions are stored in database it would be deleted.
Maybe when i go in production mode and all the permissions are fixed then i should make a seeder, but now when developing How to backup the permissions so after refresh it doesn't go a way?

**Comment by jeffgreco13** [comment]
@ehs4nm 
Please provide a screenshot. Is this happening within the Sanctum widget?
