### ISSUE TITLE
Config not serializable

### ISSUE THREAD

**Issue by ap1969** [jeffgreco13/filament-breezy#331]
Hi Jeff, 

I've got the above error, which I know some people have had before, when running artisan config:cache.

The full errror is:

``` LogicException

  Your configuration files are not serializable.

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:73
     69▕             require $configPath;
     70▕         } catch (Throwable $e) {
     71▕             $this->files->delete($configPath);
     72▕
  ➜  73▕             throw new LogicException('Your configuration files are not serializable.', 0, $e);
     74▕         }
     75▕
     76▕         $this->components->info('Configuration cached successfully.');
     77▕     }

  1   bootstrap/cache/config.php:156
      Error::("Call to undefined method Jeffgreco13\FilamentBreezy\BreezyCore::__set_state()")
      +13 vendor frames

  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

```

In looking at the other tickets, I can't seem to find a specific reason nor fix for it. I've tried all the usual things of deleting the bootstrap/cache/config.php file, but the problem remains.

Any thoughts?

Regards,
Andy

**Comment by jeffgreco13** [comment]
Are you using Filament v3 or v2?

In Breezy v2 there is no need for a config file anymore so that can be deleted if you're using the latest versions.

**Comment by ap1969** [comment]
Thanks Jeff, that was it.

I'll read the release notes in future!

**Comment by krognome** [comment]
There should be a need for config bc I can not find profile_page_icon anywhere now!!
