### ISSUE TITLE
2FA: Filament's Notification and Profile menus are visible before 2FA is completed

### ISSUE THREAD

**Issue by jackwh** [jeffgreco13/filament-breezy#334]
After entering their username and password, the user is taken to the 2FA screen. This didn't use to show anything more than the token input field, but recently I noticed the Notification and Profile menus have now started appearing.

You can click to access them and open notifications, despite the user not having completed 2FA. I'm not sure if something changed in Filament core or elsewhere as this just seemed to show up after running `composer update` recently.

**Comment by binaryfire** [comment]
Hi @JackWH. I'm having the same problem. Did you figure out a solution?

**Comment by jackwh** [comment]
@binaryfire Thanks for your Filament PR! 👍 I just submitted #356 to make your fix permanent.
