### ISSUE TITLE
Bug : User Avatar Doesn't Show in edit profile page

### ISSUE THREAD

**Issue by AmbitiousFlowDev** [jeffgreco13/filament-breezy#363]
![Capture](https://github.com/jeffgreco13/filament-breezy/assets/59917135/5ec95b07-0ebf-4f19-a2be-4f5141345650)

Hello , am having a difficulty trying to set the avatar in the edit form at profile page

```php
public function getFilamentAvatarUrl(): ?string
    {
        return $this->avatar_url ? Storage::url("$this->avatar_url") : null;
    }
```

i've also done storage:link

**Comment by AmbitiousFlowDev** [comment]
I've Figure it out 
I just used Laravel Herd and php artisan storage link Storage Link

**Comment by mateuslecchi** [comment]
I'm my case, 

The avatar is showing on de navbar but not in the edit, keeps loading eternally
![avatar](https://github.com/user-attachments/assets/a727f415-c2dd-4d4a-ac12-376c5825bb2e)

**Comment by bfarrgaynor** [comment]
I had the same issue as @mateuslecchi . It turned out that my APP_URL was set to http:// but I was accessing the page on https://. Check your .env for your project and make sure that the APP_URL value matches the domain you are viewing it on exactly.
