### ISSUE TITLE
Overriding the register class route and it does not load

### ISSUE THREAD

**Issue by ehs4nm** [jeffgreco13/filament-breezy#37]
I am trying to use another fields for my registration form, like mobile instead of email. 
I tried to override the class registration, creating a Register class in `App\Http\Livewire\Auth` and extending FilamentBreezyRegister.
I registered a route for the /register in web.php: `Route::get('/register', App\Http\Livewire\Auth\Register::class)`. But the route doesn't work, instead it goes with the package default route and the default Register class.
If i load my Package ServiceProviders before the RoutingServiceProvider, i will be able to override the Package routes within my routes but i guess there should be a better way that I'm missing.

Sorry for the mess before, i mistook the packages name. Thanks for the awesome work you have done.

**Comment by jeffgreco13** [comment]
@ehs4nm do not register a new route in your web.php file. Instead, once you have properly extended the class (as you have done) you have to publish the config then update the registration_path to use your class instead of the one from Breezy.
