### ISSUE TITLE
Email verify with id/hash route redirects without updating users table?

### ISSUE THREAD

**Issue by ChrisHardie** [jeffgreco13/filament-breezy#53]
Hi. I suspect I'm doing something wrong, but I've installed this package as instructed, added MustVerifyEmail to the User role, updated the filament config to use the new Login class, and marked all of Filament as protected by EnsureEmailIsVerified middleware. When I try to login as an existing user I get the prompt to initiate a new verification email, the email arrives, and has the proper format (`https://mysite.test/admin/email/verify/<user_id>/<hash>?expires=<timestamp>&signature=<signature>`). 

But when I click on that verify link, I'm just 302 redirected to `/admin/login` and the users table is not updated to reflect the verification.

I've verified that the full route exists as expected. Telescope says of the request:

```
Controller Action 
JeffGreco13\FilamentBreezy\Http\Controllers\EmailVerificationController@__invoke

Middleware 
Illuminate\Cookie\Middleware\EncryptCookies, Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse, Illuminate\Session\Middleware\StartSession, Illuminate\Session\Middleware\AuthenticateSession, Illuminate\View\Middleware\ShareErrorsFromSession, Illuminate\Foundation\Http\Middleware\VerifyCsrfToken, Illuminate\Routing\Middleware\SubstituteBindings, Filament\Http\Middleware\DispatchServingFilamentEvent, Filament\Http\Middleware\MirrorConfigToSubpackages, Filament\Http\Middleware\Authenticate, signed
```

Is there something else I need to do to make sure the User model is updated as verified?

Thank you.

**Comment by jeffgreco13** [comment]
Are you in the Filament Discord? I could provide some assistance there.

My first hunch is that you added the middleware to the base group in Filament whereas it should be in auth.

Provide a sample of your Filament config where you added the middleware path. Also make sure you're on the latest version of Breezy and you've cleared your config cache

**Comment by ChrisHardie** [comment]
Here's from `config/filament.php`:

```
    'middleware' => [
        'auth' => [
            Authenticate::class,
            Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        ],
        'base' => [
            EncryptCookies::class,
            AddQueuedCookiesToResponse::class,
            StartSession::class,
            AuthenticateSession::class,
            ShareErrorsFromSession::class,
            VerifyCsrfToken::class,
            SubstituteBindings::class,
            DispatchServingFilamentEvent::class,
            MirrorConfigToSubpackages::class,
        ],
    ],
```

And yes, I've made sure to clear the config cache between changes/attempts.
I'll ping you in Discord. Thanks!

**Comment by jeffgreco13** [comment]
When you're redirected to /admin/login was the user verified once you logged in? This might actually be the intended logic.

If the session is invalid when trying to verify it will direct the user to login again to initiate a new valid session, but once the user is logged in they are now verified. Can you check that?

**Comment by jeffgreco13** [comment]
@ChrisHardie any update on this issue? Will close it otherwise.
Thanks.

**Comment by austincarpenter** [comment]
Having the same issue.
