### ISSUE TITLE
When using usernames, profile attempts to update email

### ISSUE THREAD

**Issue by andycowan** [jeffgreco13/filament-breezy#61]
I've set login_fallback_field in the config to 'username'

Login works as expected.

On the Profile page, the second field is hardcoded to 'email' rather than obeying the login field config setting.

```php
protected function getUpdateProfileFormSchema(): array
    {
        return [
            Forms\Components\TextInput::make("name")
                ->label(__('filament-breezy::default.fields.name')),
            Forms\Components\TextInput::make("email")->unique(ignorable: $this->user)
                ->label(__('filament-breezy::default.fields.email')),
        ];
    }
```

Should this not follow the fallback_login_field setting in the config?

Happy to submit a PR.

**Comment by jeffgreco13** [comment]
Merged from #62
