### ISSUE TITLE
Auto login when registering is not taking into account the auth guard selected

### ISSUE THREAD

**Issue by carlosmarkez1** [jeffgreco13/filament-breezy#70]
Hello! 

I'm using on filament a different model (UserAdminPanel.php) than the basic one (User.php) that uses "session" instead of "jwt". When I register a person, it stores the user on DB correctly and tries automatically to make the login but it fails.

Then the normal login works with the created user, so I believe it's an error of abstraction on the plugin.

![image](https://user-images.githubusercontent.com/55148290/170688852-1ef49aa4-1c33-40b9-90d6-276497ec5e90.png)

![image](https://user-images.githubusercontent.com/55148290/170689186-60a8a4c6-f4fe-4429-a69b-ce2d1749126c.png)

![image](https://user-images.githubusercontent.com/55148290/170689240-5507697c-d173-4dd2-8a24-b52bd8c9a513.png)

![image](https://user-images.githubusercontent.com/55148290/170689603-d15758db-224c-426f-b6b3-44fe61b48ce2.png)

![image](https://user-images.githubusercontent.com/55148290/170689405-537352f5-6cd2-4b28-a66d-3d82da7eda71.png)

Thank you in advance!

**Comment by jeffgreco13** [comment]
I've located the abstraction issue and updated the post-registration login action to now use `Filament::auth()->login()`
