### ISSUE TITLE
Sanctum tokens do not support custom PersonalAccessToken models

### ISSUE THREAD

**Issue by JackWH** [jeffgreco13/filament-breezy#88]
Using Sanctum, it's possible to define a custom model to use for personal access tokens. In the `boot()` method of a service provider, Laravel's docs note that you can do so like this:

`Sanctum::usePersonalAccessTokenModel(\App\Models\CustomTokenModel::class);`

However, this isn't respected by the Filament Breezy package, which is hard-coded to return a `Laravel\Sanctum\PersonalAccessToken` class. Instead, I think it should probably reference `Laravel\Sanctum::$personalAccessTokenModel`.

Thanks for a great package :)

**Comment by jeffgreco13** [comment]
hey @JackWH thanks!
And thanks to @bfiessinger this has been fixed in #89

**Comment by bfiessinger** [comment]
@jeffgreco13 I don't think my PR references this issue. The problem @JackWH issues here is about overriding the default [Sanctum `PersonalAccessToken` model ](https://laravel.com/docs/9.x/sanctum#overriding-default-models)

**Comment by bfiessinger** [comment]
As you can see here https://github.com/laravel/sanctum/blob/863b610662bc09091fb73188f127d65eb64d3398/src/Sanctum.php#L82-L91 the currently used `PersonalAccessToken` Model can be referenced with `Laravel\Sanctum::$personalAccessTokenModel` like described by @JackWH
