### ISSUE TITLE
Some strings are not translatable

### ISSUE THREAD

**Issue by underdpt** [jeffgreco13/filament-breezy#9]
Hello,

I'm implementing this package on my filament app, and found that some strings cannot be translated as they're not on the lang file. These are (that I know):

- Account
- My profile
- Profile
- Or sign in to your account
- Check your inbox for instructions.
- Error: please try again later.
- Please wait before trying again.
- User with this email not found.

I have been unable to translate using a json file as I usually do with "automated" filament strings (like menu links or page headers).

I'm willing to contribute a translation to spanish, would love to have all the strings translated.

**Comment by ehs4nm** [comment]
where are the translation files? i cant find them in default dir (REsources/views/vendor/filament-breezy/)

**Comment by underdpt** [comment]
@ehs4nm they're on [`resources/lang/`](https://github.com/jeffgreco13/filament-breezy/tree/1.x/resources/lang)

**Comment by ehs4nm** [comment]
where could i overnight them other than the in the vendor? so in any updates or new installation lang folder doesn't removed.
so when i move the project to some where else the lang files be in my own resources/views/lang

**Comment by jeffgreco13** [comment]
This is corrected in the latest release by @felipe-balloni
