### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'xxxxxxxxxx@gmail.com' for key 'users_email_unique'

### ISSUE THREAD

**Issue by LittleHans8** [jeffgreco13/filament-breezy#92]
I suggest that we should check whether the email record exists in the database before updating My PROFILE Page. Otherwise, if we enter an existing email, the database will throw a uniqueness error.

**Comment by jeffgreco13** [comment]
Hello @LittleHans8 
Are you suggesting that we validate the email on MY PROFILE reactively as it is entered?
I'm not sure i understand the issue.

**Comment by LittleHans8** [comment]
Hi @jeffgreco13 , I mean validate the email when updating, I fixed this problem on [fix: validate email uniqueness #93](https://github.com/jeffgreco13/filament-breezy/pull/93).

**Comment by jeffgreco13** [comment]
Fixed in 1.4
